version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      # dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/app
    depends_on:
      - api
    ports:
      - 3000:3000

  api:
    container_name: api
    restart: always
    build:
      context: ./server
    ports:
      - 5001:5001
    depends_on:
      - db
    volumes:
      - ./server/src:/app/src
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres


  db:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - data:/data/db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes: 
 data: {}